modLoader="kotlinforforge"
loaderVersion="[${kotlin_for_forge_version},)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="protected-pvp"
description="Protection mod for PvP"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="SERVER"

[[dependencies.${mod_id}]]
modId="irons_spellbooks"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="hazennstuff"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="hazentouvelib"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="SERVER"
